### ISSUE TITLE
Email needed

### ISSUE THREAD

**Issue by ghost** [jparicka/blockchain#7]
Hey I had a few doubts regarding this repository, if you could provide me with your email address, I could mail them to you, will be waiting for your reply, thanks :D

**Comment by janfilips** [comment]
It’s ***@***.***

Jan

**Comment by ghost** [comment]
I'm sorry but, that isn't a valid email, if you think I'm joking about it, I'm not lmao.

**Comment by janfilips** [comment]
Lol joking about what?  :)

The email is ***@***.*** ***@***.***> 

Looking forward to you email

**Comment by janfilips** [comment]
I see you cannot see the email.  It's janfilipsgt@gmail.com

**Comment by ghost** [comment]
Oh thanks, my bad.
